/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamsRouteImport } from './routes/_app.teams'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppHeatmapsRouteImport } from './routes/_app.heatmaps'
import { Route as AppFieldsRouteImport } from './routes/_app.fields'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClubsRouteImport } from './routes/_app.clubs'
import { Route as AppAthletesRouteImport } from './routes/_app.athletes'
import { Route as AppTeamsTeamIdRouteImport } from './routes/_app.teams.$teamId'
import { Route as AppClubsClubIdRouteImport } from './routes/_app.clubs.$clubId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppHeatmapsRoute = AppHeatmapsRouteImport.update({
  id: '/heatmaps',
  path: '/heatmaps',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldsRoute = AppFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsRoute = AppClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AppRoute,
} as any)
const AppAthletesRoute = AppAthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsTeamIdRoute = AppTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => AppTeamsRoute,
} as any)
const AppClubsClubIdRoute = AppClubsClubIdRouteImport.update({
  id: '/$clubId',
  path: '/$clubId',
  getParentRoute: () => AppClubsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/athletes': typeof AppAthletesRoute
  '/clubs': typeof AppClubsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/fields': typeof AppFieldsRoute
  '/heatmaps': typeof AppHeatmapsRoute
  '/reports': typeof AppReportsRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/teams': typeof AppTeamsRouteWithChildren
  '/clubs/$clubId': typeof AppClubsClubIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/athletes': typeof AppAthletesRoute
  '/clubs': typeof AppClubsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/fields': typeof AppFieldsRoute
  '/heatmaps': typeof AppHeatmapsRoute
  '/reports': typeof AppReportsRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/teams': typeof AppTeamsRouteWithChildren
  '/clubs/$clubId': typeof AppClubsClubIdRoute
  '/teams/$teamId': typeof AppTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/athletes': typeof AppAthletesRoute
  '/_app/clubs': typeof AppClubsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fields': typeof AppFieldsRoute
  '/_app/heatmaps': typeof AppHeatmapsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/teams': typeof AppTeamsRouteWithChildren
  '/_app/clubs/$clubId': typeof AppClubsClubIdRoute
  '/_app/teams/$teamId': typeof AppTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/athletes'
    | '/clubs'
    | '/dashboard'
    | '/fields'
    | '/heatmaps'
    | '/reports'
    | '/sessions'
    | '/settings'
    | '/teams'
    | '/clubs/$clubId'
    | '/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/athletes'
    | '/clubs'
    | '/dashboard'
    | '/fields'
    | '/heatmaps'
    | '/reports'
    | '/sessions'
    | '/settings'
    | '/teams'
    | '/clubs/$clubId'
    | '/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/athletes'
    | '/_app/clubs'
    | '/_app/dashboard'
    | '/_app/fields'
    | '/_app/heatmaps'
    | '/_app/reports'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/teams'
    | '/_app/clubs/$clubId'
    | '/_app/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/heatmaps': {
      id: '/_app/heatmaps'
      path: '/heatmaps'
      fullPath: '/heatmaps'
      preLoaderRoute: typeof AppHeatmapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fields': {
      id: '/_app/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof AppFieldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clubs': {
      id: '/_app/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof AppClubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/athletes': {
      id: '/_app/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AppAthletesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams/$teamId': {
      id: '/_app/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AppTeamsTeamIdRouteImport
      parentRoute: typeof AppTeamsRoute
    }
    '/_app/clubs/$clubId': {
      id: '/_app/clubs/$clubId'
      path: '/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof AppClubsClubIdRouteImport
      parentRoute: typeof AppClubsRoute
    }
  }
}

interface AppClubsRouteChildren {
  AppClubsClubIdRoute: typeof AppClubsClubIdRoute
}

const AppClubsRouteChildren: AppClubsRouteChildren = {
  AppClubsClubIdRoute: AppClubsClubIdRoute,
}

const AppClubsRouteWithChildren = AppClubsRoute._addFileChildren(
  AppClubsRouteChildren,
)

interface AppTeamsRouteChildren {
  AppTeamsTeamIdRoute: typeof AppTeamsTeamIdRoute
}

const AppTeamsRouteChildren: AppTeamsRouteChildren = {
  AppTeamsTeamIdRoute: AppTeamsTeamIdRoute,
}

const AppTeamsRouteWithChildren = AppTeamsRoute._addFileChildren(
  AppTeamsRouteChildren,
)

interface AppRouteChildren {
  AppAthletesRoute: typeof AppAthletesRoute
  AppClubsRoute: typeof AppClubsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFieldsRoute: typeof AppFieldsRoute
  AppHeatmapsRoute: typeof AppHeatmapsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamsRoute: typeof AppTeamsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAthletesRoute: AppAthletesRoute,
  AppClubsRoute: AppClubsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFieldsRoute: AppFieldsRoute,
  AppHeatmapsRoute: AppHeatmapsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamsRoute: AppTeamsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
